### ISSUE TITLE
fatal error: 'sys/inotify.h' file not found

### ISSUE THREAD

**Issue by MinTate** [TUSSON/android-event-recorder#2]
Hello, Thanks for your share.

The issue is happened when i try to compile the project by the source code. So i want to know you build environment.

MY ENV: Mac OS 10.13.5

Thanks!

**Comment by TUSSON** [comment]
Because I was doing android development, I compiled it directly in the android open source code.[Establishing a Build Environment | Android Open Source Project](https://source.android.com/setup/build/initializing)

You can try [ndk-build](https://developer.android.com/ndk/guides/ndk-build), which is simpler than compiling in android source code.

**Comment by MinTate** [comment]
> Because I was doing android development, I compiled it directly in the android open source code.[Establishing a Build Environment | Android Open Source Project](https://source.android.com/setup/build/initializing)
> 
> You can try [ndk-build](https://developer.android.com/ndk/guides/ndk-build), which is simpler than compiling in android source code.

Thanks，I had compiled successfully by ndk-build in ubuntu machine.
